### ISSUE TITLE
Edit Home Page based on M2 class discussion

### ISSUE THREAD

**Issue by clint-morimoto** [brain-food/brain-food#36]
Below the "Use food to level up your brain" header:
-> Before user is logged in, perhaps a subheader saying to login to access the site
-> After user is logged in, subheader should briefly tell user what they can do next (view recipes, places for ingredients/meals, or add something to the braintrust)

**Comment by KeaUehara** [comment]
Added buttons for each of the pages mentioned above.
More words can be added later if necessary.
